# Extracción, tranformación y Carga de datos

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd '/content/drive/MyDrive/Trabajo_de_Integracion_Curricular/Data-Mining-System-SETEC-main/3_data_preprocesing_module'

/content/drive/MyDrive/Trabajo_de_Integracion_Curricular/Data-Mining-System-SETEC-main/3_data_preprocesing_module

## Librerías

In [1]:
import pandas as pd
import numpy as np
import os

## Ruta de archivos

In [2]:
path = os.path.abspath(os.path.join(os.getcwd(), '..','2_data_understanding_module','collecting_initial_data','existing_data','DIRTY_DATA'))
path_additional_data = os.path.abspath(os.path.join(os.getcwd(), '..','2_data_understanding_module','collecting_initial_data','additional_data'))
path_etl = os.path.abspath(os.path.join(os.getcwd(),'CLEANED_DATA'))

# Datos adicionales

In [ ]:
def get_hours(x,y):
    val = y.replace(' ','')
    if val[-1]=='h':
        return val[:-1]
    elif val.isdigit():
        return val
    
    val = x.replace(' ','')
    if val[-1]=='h':
        return val[:-1]
    elif val.isdigit():
        return val
    else:
        return val

In [ ]:
# Selecting Data
df_coec = pd.read_csv(os.path.join(path_additional_data,'costo_oferta_educacion_continua.csv'))
df_coec = df_coec[['Areas de Formación', 'Nombre  de los Programas','Modalidad', 'Tiempo de duración','Duración programa',' Precio ']]
df_coec = df_coec.rename(columns={' Precio ':'Precio'})
for col in df_coec.columns:
    df_coec[col] = df_coec[col].str.lower()
    aux = df_coec[col][0]
    for i in range(df_coec.shape[0]):
        if pd.isna(df_coec[col][i]):
            df_coec[col][i] = aux
        else:
            aux = df_coec[col][i]
            

df_coec = df_coec[(df_coec['Areas de Formación'].str.contains('tecnol|tics', regex=True))]
df_coec = df_coec[(df_coec['Precio'].str.contains('^(?:(?!llamar).)+$', regex=True))]

In [ ]:
df_coec['carga_horaria'] = df_coec.apply(lambda x: get_hours(x['Tiempo de duración'], x['Duración programa']), axis=1)

# CAMBIO MANUAL DE DATOS
df_coec['carga_horaria'].iloc[-1] = 40

In [ ]:
df_coec = df_coec.drop(['Areas de Formación','Tiempo de duración','Duración programa'],axis=1)

In [ ]:
df_coec['Precio'] = df_coec['Precio'].str.replace('$','',regex=True)
df_coec['Precio'] = df_coec['Precio'].str.replace(',','',regex=True)
df_coec['Precio'] = df_coec['Precio'].str.replace(' ','',regex=True)
df_coec['Precio'] = df_coec['Precio'].astype('float64')

In [ ]:
df_coec['carga_horaria'] = df_coec['carga_horaria'].astype('int32')
df_coec['precio'] = df_coec.pop('Precio')

In [ ]:
df_coec['precio_por_hora'] = df_coec.apply(lambda x: np.round(x['precio']/x['carga_horaria'],decimals = 2), axis=1)

In [ ]:
df_coec['Modalidad'] = df_coec['Modalidad'].replace({'presencial':'PRESENCIAL','en vivo':'ONLINE','virtual':'ONLINE','online':'ONLINE'})

In [ ]:
df_coec = df_coec.rename(columns={'Nombre  de los Programas':'curso','Modalidad':'modalidad'})

In [ ]:
df_coec.to_csv(os.path.join(path_etl,'costos_cursos_educacion_continua.csv'),index=False)

## Catálogo Nacional de Cualificaciones - CNC 

- CNC para Operadores de Capacitación - CNCOC
- CNC para Organismos Evaluadores de  la Conformidad - CNCOEC
- CNC  Perfiles Inhabilitados - CNCPI

### ETL CNCOC

In [ ]:
df_cncoc = pd.read_csv(os.path.join(path,'cncoc.csv'))
df_cncoc = df_cncoc.rename(columns={'Familia':'familia','Perfil':'perfil','Competenecia Laboral':'competenecia_laboral','Sector':'sector'})
df_cncoc.insert(4, 'tipo', "oc")
df_cncoc.insert(5, 'estado', "habilitado")

In [ ]:
#df_cncoc.info()

### ETL CNCOEC

In [ ]:
df_cncoec = pd.read_csv(os.path.join(path,'cncoec0.csv'))
df_cncoec = df_cncoec.drop(['Unnamed: 0','Descargar Perfil','Descargar Esquema'],axis=1)
df_cncoec = df_cncoec.rename(columns={'Familia':'familia','Perfil':'perfil','Competenecia Laboral':'competenecia_laboral','Sector':'sector'})
df_cncoec.insert(4, 'tipo', "oec")
df_cncoec.insert(5, 'estado', "habilitado")

In [ ]:
#df_cncoec.info()

### ETL CNCPI

In [ ]:
df_cncpi = pd.read_csv(os.path.join(path,'cncpi0.csv'))
df_cncpi = df_cncpi.drop(['Descargar Perfil'],axis=1)
df_cncpi = df_cncpi.rename(columns={'Familia':'familia','Perfil':'perfil','Competenecia Laboral':'competenecia_laboral','Sector':'sector'})
df_cncpi.insert(1, 'competenecia_laboral', "")
df_cncpi.insert(4, 'tipo', "")
df_cncpi.insert(5, 'estado', "inhabilidato")

In [ ]:
#df_cncpi.info()

 ### **CNC** - INTEGRACIÓN DE DATOS

In [ ]:
df_cnc = pd.concat([df_cncoc,df_cncoec,df_cncpi],axis=0)
df_cnc = df_cnc.apply(lambda x: x.astype(str).str.lower())

In [ ]:
df_cnc = df_cnc.drop_duplicates()

In [ ]:
#df_cnc.info()

### Guardar datos CNC

In [ ]:
df_cnc.to_csv(os.path.join(path_etl,'cnc.csv'),index=False)

## Operadores de Capacitación - OC

• [Operadores de Capacitación](http://portal.trabajo.gob.ec/setec-portal-web/pages/operadoresCapacitacion.jsf#j_idt24:j_idt25) - OC

• [OC - Suspendidos](http://portal.trabajo.gob.ec/setec-portal-web/pages/operadoresCapacitacion.jsf#j_idt24:j_idt125) - OCS

• [OC - Finalizaron su vigencia de Calificación](http://portal.trabajo.gob.ec/setec-portal-web/pages/operadoresCapacitacion.jsf#j_idt24:j_idt134) - OCF

• [OC - Cancelados](http://portal.trabajo.gob.ec/setec-portal-web/pages/operadoresCapacitacion.jsf#j_idt24:j_idt144) - OCC

### ETL OC

In [3]:
df_oc = pd.read_csv(os.path.join(path,'oc0.csv'))
#df_oc = df_oc.drop(['Descargar','Detalle'],axis=1)
df_oc['Celular'] = df_oc['Celular'].astype('object')
df_oc["Nombre_Comercial"].fillna("Sin Nombre Comercial", inplace = True) 
df_oc.insert(9, 'estado', df_oc.pop('Estado'))
df_oc = df_oc.rename(columns={'RUC_o_Codigo':'ruc_o_codigo'})
df_oc = df_oc.rename(columns={'Telefono':'telefono'})
df_oc = df_oc.rename(columns={'Correo_Electronico':'correo_electronico'})
df_oc = df_oc.rename(columns={'Fecha_Resolucion':'fecha_resolucion'})
df_oc = df_oc.rename(columns={'Numero_Resolucion':'numero_resolucion'})
df_oc = df_oc.rename(columns={'Canton':'canton'})
df_oc = df_oc.rename(columns={'Nombre_Comercial':'nombre_comercial'})
df_oc = df_oc.rename(columns={'Razon_Social':'razon_social'})
df_oc = df_oc.rename(columns={'Celular':'celular'})

In [5]:
#df_oc.info()

### ETL OCS

In [6]:
df_ocs = pd.read_csv(os.path.join(path,'ocs.csv'))
df_ocs['RUC / Código'] = df_ocs['RUC / Código'].astype('object')
df_ocs.insert(2, 'nombre_comercial', 'Sin Nombre Comercial')
df_ocs.insert(3, 'telefono', 'Sin Teléfono')
df_ocs.insert(4, 'celular', 'Sin Celular')
df_ocs.insert(5, 'correo_electronico', 'Sin Email')
df_ocs.insert(6, 'numero_resolucion', 'Sin Número Resolución')
df_ocs.insert(7, 'fecha_resolucion', 'Sin Fecha Resolución')
df_ocs.insert(8, 'canton', 'Sin Cantón')
df_ocs = df_ocs.rename(columns={'Razón Social':'razon_social'})
df_ocs = df_ocs.rename(columns={'RUC / Código':'ruc_o_codigo'})
df_ocs = df_ocs.rename(columns={'Estado':'estado'})

In [7]:
#df_ocs.info()

### ETL OCC

In [8]:
df_occ = pd.read_csv(os.path.join(path,'occ.csv'))
df_occ['RUC / Código'] = df_occ['RUC / Código'].astype('object')
df_occ.insert(2, 'nombre_comercial', 'Sin Nombre Comercial')
df_occ.insert(3, 'telefono', 'Sin Teléfono')
df_occ.insert(4, 'celular', 'Sin Celular')
df_occ.insert(5, 'correo_electronico', 'Sin Email')
df_occ.insert(6, 'numero_resolucion', 'Sin Número Resolución')
df_occ.insert(7, 'fecha_resolucion', 'Sin Fecha Resolución')
df_occ.insert(8, 'canton', 'Sin Cantón')
df_occ = df_occ.rename(columns={'Razón Social':'razon_social'})
df_occ = df_occ.rename(columns={'RUC / Código':'ruc_o_codigo'})
df_occ = df_occ.rename(columns={'Estado':'estado'})

In [9]:
#df_occ.info()

### ETL OCF

In [10]:
df_ocf = pd.read_csv(os.path.join(path,'ocf0.csv'))
df_ocf.insert(2, 'nombre_comercial', 'Sin Nombre Comercial')
df_ocf.insert(3, 'telefono', 'Sin Teléfono')
df_ocf.insert(4, 'celular', 'Sin Celular')
df_ocf.insert(5, 'correo_electronico', 'Sin Correo Electronico')
df_ocf.insert(6, 'numero_resolucion', 'Sin Número Resolución')
df_ocf.insert(7, 'fecha_resolucion', 'Sin Fecha Resolución')
df_ocf.insert(8, 'canton', 'Sin Cantón')
df_ocf = df_ocf.rename(columns={'Razón Social':'razon_social'})
df_ocf = df_ocf.rename(columns={'RUC / Código':'ruc_o_codigo'})
df_ocf = df_ocf.rename(columns={'Estado':'estado'})

In [11]:
df_ocf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ruc_o_codigo        178 non-null    object
 1   razon_social        178 non-null    object
 2   nombre_comercial    178 non-null    object
 3   telefono            178 non-null    object
 4   celular             178 non-null    object
 5   correo_electronico  178 non-null    object
 6   numero_resolucion   178 non-null    object
 7   fecha_resolucion    178 non-null    object
 8   canton              178 non-null    object
 9   estado              178 non-null    object
dtypes: object(10)
memory usage: 14.0+ KB

### DATOS LIMPIOS OC

In [12]:
df_OC = pd.concat([df_oc,df_ocs,df_ocf,df_occ],axis=0)
df_OC = df_OC.apply(lambda x: x.astype(str).str.lower())
df_OC = df_OC.drop_duplicates()

In [18]:
#df_OC.head()
#df_OC.info()

### Guardar datos OC

In [15]:
df_OC.to_csv(os.path.join(path_etl,'oc.csv'),index=False)

### ETL OC_CC

In [16]:
df_oc_cc = pd.read_csv(os.path.join(path,'oc_cc0.csv'))
df_oc_cc = df_oc_cc.drop_duplicates()
df_oc_cc = df_oc_cc.dropna(subset=['area','especialidad','curso','modalidad','carga_horaria'])
df_oc_cc['modalidad'] = df_oc_cc['modalidad'].replace(['VIRTUAL'], 'ONLINE')
df_oc_cc = df_oc_cc.apply(lambda x: x.astype(str).str.lower())
df_oc_cc['carga_horaria'] = df_oc_cc['carga_horaria'].astype('float64')
df_oc_cc = df_oc_cc.drop_duplicates()

In [19]:
#df_oc_cc.head()
#df_oc_cc.info()

### Guardar datos OC_CC

In [20]:
df_oc_cc.to_csv(os.path.join(path_etl,'oc_cc.csv'),index=False)

### ETL OC_CL

In [21]:
#df_oc_cl = pd.read_csv(os.path.join(path,'oc_cl0.csv'))
#df_oc_cl = df_oc_cl.drop_duplicates()
#df_oc_cl = df_oc_cl.rename(columns={'Razón Social':'Razon_Social'})
#df_oc_cl = df_oc_cl.rename(columns={'Ruc / Código':'RUC_o_Codigo'})
#df_oc_cl.info()

In [22]:
#df_oc_cl.describe(include='all')

### Guardar datos OC_CL

In [ ]:
#df_oc_cl.to_csv(path_etl+'oc_cl.csv',index=False)

## Personas Capacitadas por OC - PCOC

• [Búsqueda Personas Capacitadas](http://portal.trabajo.gob.ec/setec-portal-web/pages/personasCapacitadasOperadores.jsf#j_idt24:j_idt25) - PCOC

In [ ]:
df_pcoc = pd.read_csv(path+'pcoc.csv')
df_pcoc = df_pcoc.drop(['Unnamed: 0'],axis=1)
df_pcoc["Número Documento"].fillna("Sin Número Documento", inplace = True)
df_pcoc["Apellidos / Nombres"].fillna("Sin Apellidos / Nombres", inplace = True)
df_pcoc["Número Horas"].astype('float64')
df_pcoc["Razón Social OC"].fillna("Sin Razón Social OC", inplace = True)
df_pcoc["Nombre Comercial OC"].fillna("Sin Nombre Comercial OC", inplace = True)
df_pcoc = df_pcoc.rename(columns={'Número Documento':'Numero_Documento'})
df_pcoc = df_pcoc.rename(columns={'Apellidos / Nombres':'Apellidos_Nombres'})
df_pcoc = df_pcoc.rename(columns={'Tipo Capacitación':'Tipo_Capacitacion'})
df_pcoc = df_pcoc.rename(columns={'Nombre Curso / Perfil':'Nombre_Curso_Perfil'})
df_pcoc = df_pcoc.rename(columns={'Número Horas':'Numero_Horas'})
df_pcoc = df_pcoc.rename(columns={'Razón Social OC':'Razon_Social_OC'})
df_pcoc = df_pcoc.rename(columns={'Nombre Comercial OC':'Nombre_Comercial_OC'})
df_pcoc = df_pcoc.rename(columns={'Número Certificado':'Numero_Certificado'})
df_pcoc = df_pcoc.drop_duplicates()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 251989 entries, 0 to 251988
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Numero_Documento     251989 non-null  object
 1   Apellidos_Nombres    251989 non-null  object
 2   Tipo_Capacitacion    251989 non-null  object
 3   Nombre_Curso_Perfil  251989 non-null  object
 4   Numero_Horas         251872 non-null  float64
 5   Razon_Social_OC      251989 non-null  object
 6   Nombre_Comercial_OC  251989 non-null  object
 7   Numero_Certificado   251989 non-null  object
dtypes: float64(1), object(7)
memory usage: 17.3+ MB

In [ ]:
df_pcoc.info()

In [ ]:
df_pcoc.to_csv(path_etl+'pcoc.csv',index=False)

### Datos Número Documento y Apellidos/Nombre

In [ ]:
df_d_n_pcoc = pd.read_csv(path_etl+'pcoc.csv')
df_d_n_pcoc = df_d_n_pcoc[['Numero_Documento','Apellidos_Nombres']]
df_d_n_pcoc['size_doc'] = df_d_n_pcoc['Numero_Documento'].apply(lambda doc: len(doc))
df_d_n_pcoc = df_d_n_pcoc[df_d_n_pcoc['size_doc']==10]
df_d_n_pcoc = df_d_n_pcoc.drop_duplicates(['Numero_Documento'], keep='last')
df_d_n_pcoc.pop('size_doc')
df_d_n_pcoc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 181304 entries, 0 to 251987
Data columns (total 2 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Numero_Documento   181304 non-null  object
 1   Apellidos_Nombres  181304 non-null  object
dtypes: object(2)
memory usage: 4.1+ MB

In [ ]:
df_d_n_pcoc.to_csv(path_etl+'doc_name_pcoc.csv',index=False)

## Organismos Evaluadores de  la Conformidad - OEC

• [Organismos Evaluadores de la Conformidad](http://portal.trabajo.gob.ec/setec-portal-web/pages/evaluadoresConformidad.jsf#j_idt24:j_idt25) - OEC

• [OEC - Suspendidos](http://portal.trabajo.gob.ec/setec-portal-web/pages/evaluadoresConformidad.jsf#j_idt24:j_idt103) - OECS

• [OEC - Finalizaron su vigencia de Reconocimiento](http://portal.trabajo.gob.ec/setec-portal-web/pages/evaluadoresConformidad.jsf#j_idt24:j_idt112) - OECF

• [OEC - Cancelados](http://portal.trabajo.gob.ec/setec-portal-web/pages/evaluadoresConformidad.jsf#j_idt24:j_idt122) - OECC

### ETL OEC

In [ ]:
df_oec = pd.read_csv(path+'oec0.csv')
df_oec = df_oec.rename(columns={'Ruc / Código':'RUC_o_Codigo'})
df_oec = df_oec.drop(['Descargar','Ver Detalle'],axis=1)
df_oec['Celular'] = df_oec['Celular'].astype('object')
df_oec = df_oec.rename(columns={'Estado Resolución':'Estado'})
df_oec = df_oec.rename(columns={'Ruc / Código':'RUC_o_Codigo'})
df_oec = df_oec.rename(columns={'Razón Social':'Razon_Social'})
df_oec = df_oec.rename(columns={'Dirección':'Direccion'})
df_oec = df_oec.rename(columns={'Teléfono':'Telefono'})
df_oec = df_oec.rename(columns={'Email':'Correo_Electronico'})
df_oec = df_oec.rename(columns={'Número Resolución':'Numero_Resolucion'})
df_oec = df_oec.rename(columns={'Fecha Resolución':'Fecha_Resolucion'})
df_oec = df_oec.rename(columns={'Cantón':'Canton'})
df_oec = df_oec.drop_duplicates()
df_oec.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 221 entries, 0 to 220
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RUC_o_Codigo        221 non-null    object
 1   Razon_Social        221 non-null    object
 2   Direccion           221 non-null    object
 3   Telefono            221 non-null    object
 4   Celular             221 non-null    object
 5   Correo_Electronico  221 non-null    object
 6   Numero_Resolucion   221 non-null    object
 7   Fecha_Resolucion    221 non-null    object
 8   Canton              221 non-null    object
 9   Estado              221 non-null    object
dtypes: object(10)
memory usage: 19.0+ KB

### ETL OECS

In [ ]:
df_oecs = pd.read_csv(path+'oecs.csv')
df_oecs['RUC / Código'] = df_oecs['RUC / Código'].astype('object')
df_oecs.insert(2, 'Direccion', 'Sin Dirección')
df_oecs.insert(3, 'Telefono', 'Sin Teléfono')
df_oecs.insert(4, 'Celular', 'Sin Celular')
df_oecs.insert(5, 'Correo_Electronico', 'Sin Email')
df_oecs.insert(6, 'Numero_Resolucion', 'Sin Número Resolución')
df_oecs.insert(7, 'Fecha_Resolucion', 'Sin Fecha Resolución')
df_oecs.insert(8, 'Canton', 'Sin Cantón')  
df_oecs = df_oecs.rename(columns={'RUC / Código':'RUC_o_Codigo'})
df_oecs = df_oecs.rename(columns={'Razón Social':'Razon_Social'})                            
df_oecs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RUC_o_Codigo        4 non-null      object
 1   Razon_Social        4 non-null      object
 2   Direccion           4 non-null      object
 3   Telefono            4 non-null      object
 4   Celular             4 non-null      object
 5   Correo_Electronico  4 non-null      object
 6   Numero_Resolucion   4 non-null      object
 7   Fecha_Resolucion    4 non-null      object
 8   Canton              4 non-null      object
 9   Estado              4 non-null      object
dtypes: object(10)
memory usage: 448.0+ bytes

### ETL OECF

In [ ]:
df_oecf = pd.read_csv(path+'oecf0.csv')
df_oecf.insert(2, 'Direccion', 'Sin Dirección')
df_oecf.insert(3, 'Telefono', 'Sin Teléfono')
df_oecf.insert(4, 'Celular', 'Sin Celular')
df_oecf.insert(5, 'Correo_Electronico', 'Sin Email')
df_oecf.insert(6, 'Numero_Resolucion', 'Sin Número Resolución')
df_oecf.insert(7, 'Fecha_Resolucion', 'Sin Fecha Resolución')
df_oecf.insert(8, 'Canton', 'Sin Cantón')  
df_oecf = df_oecf.rename(columns={'RUC / Código':'RUC_o_Codigo'})
df_oecf = df_oecf.rename(columns={'Razón Social':'Razon_Social'})                          
df_oecf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RUC_o_Codigo        100 non-null    object
 1   Razon_Social        100 non-null    object
 2   Direccion           100 non-null    object
 3   Telefono            100 non-null    object
 4   Celular             100 non-null    object
 5   Correo_Electronico  100 non-null    object
 6   Numero_Resolucion   100 non-null    object
 7   Fecha_Resolucion    100 non-null    object
 8   Canton              100 non-null    object
 9   Estado              100 non-null    object
dtypes: object(10)
memory usage: 7.9+ KB

### ETL OECC

In [ ]:
df_oecc = pd.read_csv(path+'oecc.csv')
df_oecc.insert(2, 'Direccion', 'Sin Dirección')
df_oecc.insert(3, 'Telefono', 'Sin Teléfono')
df_oecc.insert(4, 'Celular', 'Sin Celular')
df_oecc.insert(5, 'Correo_Electronico', 'Sin Email')
df_oecc.insert(6, 'Numero_Resolucion', 'Sin Número Resolución')
df_oecc.insert(7, 'Fecha_Resolucion', 'Sin Fecha Resolución')
df_oecc.insert(8, 'Canton', 'Sin Cantón')  
df_oecc = df_oecc.rename(columns={'RUC / Código':'RUC_o_Codigo'})
df_oecc = df_oecc.rename(columns={'Razón Social':'Razon_Social'})                               
df_oecc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RUC_o_Codigo        14 non-null     int64
 1   Razon_Social        14 non-null     object
 2   Direccion           14 non-null     object
 3   Telefono            14 non-null     object
 4   Celular             14 non-null     object
 5   Correo_Electronico  14 non-null     object
 6   Numero_Resolucion   14 non-null     object
 7   Fecha_Resolucion    14 non-null     object
 8   Canton              14 non-null     object
 9   Estado              14 non-null     object
dtypes: int64(1), object(9)
memory usage: 1.2+ KB

### DATOS LIMPIOS OEC

In [ ]:
df_OEC = pd.concat([df_oec,df_oecs,df_oecf,df_oecc],axis=0)
df_OEC.drop_duplicates()
df_OEC.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 339 entries, 0 to 13
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RUC_o_Codigo        339 non-null    object
 1   Razon_Social        339 non-null    object
 2   Direccion           339 non-null    object
 3   Telefono            339 non-null    object
 4   Celular             339 non-null    object
 5   Correo_Electronico  339 non-null    object
 6   Numero_Resolucion   339 non-null    object
 7   Fecha_Resolucion    339 non-null    object
 8   Canton              339 non-null    object
 9   Estado              339 non-null    object
dtypes: object(10)
memory usage: 29.1+ KB

In [ ]:
df_OEC.describe(include='all')

,RUC_o_Codigo,Razon_Social,Direccion,Telefono,Celular,Correo_Electronico,Numero_Resolucion,Fecha_Resolucion,Canton,Estado
count,339,339,339,339,339,339,339,339,339,339
unique,319,318,222,214,217,221,222,120,44,4
top,17-043,INSTITUTO SUPERIOR TECNOLÓGICO BENITO JUAREZ,Sin Dirección,Sin Teléfono,Sin Celular,Sin Email,Sin Número Resolución,Sin Fecha Resolución,Sin Cantón,HABILITADO
freq,3,3,118,118,118,118,118,118,118,221

### Guardar datos OEC

In [ ]:
df_OEC.to_csv(path_etl+'oec.csv',index=False)

### ETL OEC_DR

In [ ]:
df_oec_dr = pd.read_csv(path+'oec_dr0.csv')
df_oec_dr = df_oec_dr.rename(columns={'Unnamed: 2':'Perfil','Unnamed: 3':'Esquema_de_Certificacion'})
df_oec_dr["Perfil"].fillna("Sin Perfil", inplace = True)
df_oec_dr["Esquema_de_Certificacion"].fillna("Sin Esquema de Certificación", inplace = True)
df_oec_dr = df_oec_dr.rename(columns={'Ruc / Código':'RUC_o_Codigo'})
df_oec_dr = df_oec_dr.rename(columns={'Razón Social':'Razon_Social'}) 
df_oec_dr = df_oec_dr.drop_duplicates()
df_oec_dr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 997 entries, 0 to 1204
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   RUC_o_Codigo              997 non-null    object
 1   Razon_Social              997 non-null    object
 2   Perfil                    997 non-null    object
 3   Esquema_de_Certificacion  997 non-null    object
dtypes: object(4)
memory usage: 38.9+ KB

In [ ]:
df_oec_dr.describe(include='all')

,RUC_o_Codigo,Razon_Social,Perfil,Esquema_de_Certificacion
count,997,997,997,997
unique,169,169,128,145
top,1712698271001,VALDEZ ENCALADA MILTON MANUEL,PREVENCIÓN DE RIESGOS LABORALES,PREVENCIÓN DE RIESGOS LABORALES: CONSTRUCCIÓN ...
freq,45,45,121,61

### Guardar datos OEC_DR

In [ ]:
df_oec_dr.to_csv(path_etl+'oec_dr.csv',index=False)

## Personas Certificadas por OEC - PCOEC

• [Búsqueda Personas Certificadas](http://portal.trabajo.gob.ec/setec-portal-web/pages/legitimidadCertificacion.jsf#j_idt24:j_idt25) - PCOEC

In [ ]:
df_pcoec = pd.concat([
    pd.read_csv(path+'pcoec0.csv'),
    pd.read_csv(path+'pcoec1.csv'),
    pd.read_csv(path+'pcoec2.csv'),
    pd.read_csv(path+'pcoec3.csv'),
    ],axis=0)  
df_pcoec = df_pcoec.drop(['Ver Certificado'],axis=1)
df_pcoec["Fecha Vigencia"].fillna("Sin Fecha Vigencia", inplace = True)
df_pcoec["Celular"].fillna("Sin Celular", inplace = True)
df_pcoec = df_pcoec.rename(columns={'Número Certificación':'Numero_Certificación'})
df_pcoec = df_pcoec.rename(columns={'Fecha Certificación':'Fecha_Certificacion'})
df_pcoec = df_pcoec.rename(columns={'Fecha Vigencia':'Fecha_Vigencia'})
df_pcoec = df_pcoec.rename(columns={'Ruc Organismo Evaluador':'RUC_OEC'})
df_pcoec = df_pcoec.rename(columns={'Organismo Evaluador':'OEC'})  
df_pcoec = df_pcoec.drop_duplicates()
df_pcoec.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 301573 entries, 0 to 65659
Data columns (total 8 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Nombres               301573 non-null  object
 1   Perfil                301573 non-null  object
 2   Numero_Certificación  301573 non-null  object
 3   Fecha_Certificacion   301573 non-null  object
 4   Fecha_Vigencia        301573 non-null  object
 5   Celular               301573 non-null  object
 6   RUC_OEC               301573 non-null  object
 7   OEC                   301573 non-null  object
dtypes: object(8)
memory usage: 20.7+ MB

In [ ]:
df_pcoec.describe(include='all')

,Nombres,Perfil,Numero_Certificación,Fecha_Certificacion,Fecha_Vigencia,Celular,RUC_OEC,OEC
count,301573,301573,301573,301573,301573,301573,301573,301573
unique,261907,495,301378,2139,2690,209293,316,316
top,ALCIVAR ALCIVAR HOLGER ESEQUIEL,PREVENCIÓN EN RIESGOS LABORALES,SETEC-17024-CCL-9650,27-03-2017,27-03-2021,-,1768041140001,SERVICIO ECUATORIANO DE CAPACITACIÓN PROFESION...
freq,14,88189,5,1670,1091,19580,48669,48669

### Guardar datos PCOEC

In [ ]:
df_pcoec.to_csv(path_etl+'pcoec.csv',index=False)

## Capacitadores Independientes - CI

• [Búsqueda de Capacitadores Independientes](http://portal.trabajo.gob.ec/setec-portal-web/pages/operadoresCapacitacionIndependientes.jsf#j_idt24:j_idt25) - CI

### ETL CI

In [ ]:
df_ci = pd.read_csv(path+'ci0.csv')
df_ci['Número Documento'] = df_ci['Número Documento'].astype('object')
df_ci = df_ci.drop(['Detalle'],axis=1)
df_ci = df_ci.drop(['Ver Certificado'],axis=1)
df_ci = df_ci.rename(columns={'Número Documento':'Numero_Documento'})
df_ci = df_ci.rename(columns={'Apellidos / Nombres':'Apellidos_Nombres'})
df_ci = df_ci.rename(columns={'Código Resolucion':'Codigo_Resolucion'})
df_ci = df_ci.rename(columns={'Vigencia Resolucion':'Vigencia_Resolucion'})
df_ci = df_ci.rename(columns={'Email':'Correo_Electronico'})
df_ci = df_ci.drop_duplicates()
df_ci.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1619 entries, 0 to 2969
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Numero_Documento     1619 non-null   object
 1   Apellidos_Nombres    1619 non-null   object
 2   Codigo_Resolucion    1619 non-null   object
 3   Vigencia_Resolucion  1619 non-null   object
 4   Correo_Electronico   1619 non-null   object
 5   Celular              1619 non-null   object
dtypes: object(6)
memory usage: 88.5+ KB

In [ ]:
df_ci.describe(include='all')

,Numero_Documento,Apellidos_Nombres,Codigo_Resolucion,Vigencia_Resolucion,Correo_Electronico,Celular
count,1619,1619,1619,1619,1619,1619
unique,1355,1355,1619,314,1346,1346
top,1723974893,ALVEAR SANCHEZ JEFFERSON BRAYAN,RESOLUCIÓN No. MDT-CI-CAL-2021-0115,2022-09-10,edusito20@hotmail.com,0995201124
freq,4,4,1,160,7,5

### Guardar datos CI

In [ ]:
df_ci.to_csv(path_etl+'ci.csv',index=False)

### ETL CI_LCA

In [ ]:
df_ci_lca =pd.read_csv(path+'ci_lca0.csv') 
df_ci_lca['Número Documento'] = df_ci_lca['Número Documento'].astype('object')
df_ci_lca["Nombre Curso"].fillna("Sin Nombre Curso", inplace = True)
df_ci_lca["Área"].fillna("Sin Área", inplace = True)
df_ci_lca["Especialidad"].fillna("Sin Especialidad", inplace = True)
df_ci_lca["Carga Horaria"].astype('float64')
df_ci_lca = df_ci_lca.rename(columns={'Número Documento':'Numero_Documento'})
df_ci_lca = df_ci_lca.rename(columns={'Apellidos / Nombres':'Apellidos_Nombres'})
df_ci_lca = df_ci_lca.rename(columns={'Nombre Curso':'Nombre_Curso'})
df_ci_lca = df_ci_lca.rename(columns={'Área':'Area'})
df_ci_lca = df_ci_lca.drop_duplicates()
df_ci_lca.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2934 entries, 0 to 7104
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Numero_Documento   2934 non-null   object
 1   Apellidos_Nombres  2934 non-null   object
 2   Nombre_Curso       2934 non-null   object
 3   Area               2934 non-null   object
 4   Especialidad       2934 non-null   object
 5   Carga Horaria      2913 non-null   float64
dtypes: float64(1), object(5)
memory usage: 160.5+ KB

In [ ]:
df_ci_lca.describe(include='all')

,Numero_Documento,Apellidos_Nombres,Nombre_Curso,Area,Especialidad,Carga Horaria
count,2934.0,2934,2934,2934,2934,2913.000000
unique,1355.0,1355,602,17,90,NaN
top,928364678.0,GUERRERO MAYORGA CRISTOPHER NESTOR,PREVENCIÓN DE RIESGOS LABORALES,PROCESOS INDUSTRIALES,SEGURIDAD PREVENCIÓN DE RIESGOS E HIGIENE INDU...,NaN
freq,15.0,15,119,877,842,NaN
mean,NaN,NaN,NaN,NaN,NaN,28.449022
std,NaN,NaN,NaN,NaN,NaN,12.270820
min,NaN,NaN,NaN,NaN,NaN,8.000000
25%,NaN,NaN,NaN,NaN,NaN,16.000000
50%,NaN,NaN,NaN,NaN,NaN,32.000000
75%,NaN,NaN,NaN,NaN,NaN,40.000000
max,NaN,NaN,NaN,NaN,NaN,40.000000

### Guardar datos CI_LCA

In [ ]:
df_ci_lca.to_csv(path_etl+'ci_lca.csv',index=False)

## Personas Capacitadas por CI - PCCI

• [Búsqueda de Personas Capacitadas](http://portal.trabajo.gob.ec/setec-portal-web/pages/personasCapacitadas.jsf#j_idt24:j_idt25) - PCCI

In [ ]:
df_pcci =pd.read_csv(path+'pcci.csv')
df_pcci = df_pcci.rename(columns={'Número Documento':'Numero_Documento'})
df_pcci = df_pcci.rename(columns={'Apellidos / Nombres':'Apellidos_Nombres'})
df_pcci = df_pcci.rename(columns={'Nombre Curso':'Nombre_Curso'})
df_pcci = df_pcci.rename(columns={'Número Horas':'Carga_Horaria'})
df_pcci = df_pcci.rename(columns={'Instructor / Capacitador':'Instructor_Capacitador'}) 
df_pcci = df_pcci.drop_duplicates()
df_pcci.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 140180 entries, 0 to 146009
Data columns (total 5 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Numero_Documento        140180 non-null  object
 1   Apellidos_Nombres       140180 non-null  object
 2   Nombre_Curso            140180 non-null  object
 3   Carga_Horaria           140180 non-null  int64
 4   Instructor_Capacitador  140180 non-null  object
dtypes: int64(1), object(4)
memory usage: 6.4+ MB

In [ ]:
df_pcci.describe(include='all')

,Numero_Documento,Apellidos_Nombres,Nombre_Curso,Carga_Horaria,Instructor_Capacitador
count,140180,140180,140180,140180.000000,140180
unique,101440,100920,508,NaN,1060
top,1316342730,GUEVARA TORRES EDGAR ANIBAL,PREVENCIÓN EN TRABAJO DE ALTURAS,NaN,URQUIA VALENCIA OSCAR MAURICIO
freq,27,27,10295,NaN,5192
mean,NaN,NaN,NaN,28.054573,NaN
std,NaN,NaN,NaN,14.300044,NaN
min,NaN,NaN,NaN,1.000000,NaN
25%,NaN,NaN,NaN,16.000000,NaN
50%,NaN,NaN,NaN,32.000000,NaN
75%,NaN,NaN,NaN,40.000000,NaN
max,NaN,NaN,NaN,400.000000,NaN

### Guardar datos PCCI

In [ ]:
df_pcci.to_csv(path_etl+'pcci.csv',index=False)

### Datos Número Documento y Apellidos/Nombre

In [ ]:
df_d_n_pcci = pd.read_csv(path_etl+'pcci.csv')
df_d_n_pcci = df_d_n_pcci[['Numero_Documento','Apellidos_Nombres']]
df_d_n_pcci['size_doc'] = df_d_n_pcci['Numero_Documento'].apply(lambda doc: len(doc))
df_d_n_pcci = df_d_n_pcci[df_d_n_pcci['size_doc']==10]
df_d_n_pcci = df_d_n_pcci.drop_duplicates(['Numero_Documento'], keep='last')
df_d_n_pcci.pop('size_doc')
df_d_n_pcci.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99000 entries, 0 to 140179
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Numero_Documento   99000 non-null  object
 1   Apellidos_Nombres  99000 non-null  object
dtypes: object(2)
memory usage: 2.3+ MB

In [ ]:
df_d_n_pcci.to_csv(path_etl+'doc_name_pcci.csv',index=False)